{
 "title": "IoT Data",
 "description": "temperatures and pressure from 2 points",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "House (press)",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "query": "SELECT house_pressure AS house FROM mqtt_consumer "
    }
   ]
  },
  {
   "title": "Balcony (press)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT balcony_pressure AS balcony FROM mqtt_consumer "
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT balcony_temperature AS balcony FROM mqtt_consumer \n"
    },
    {
     "query": "SELECT house_temperature AS house FROM mqtt_consumer"
    }
   ]
  }
 ]
}